[package]
name = "DuckType"
version = "0.43.0"
authors = ["Jonathan Dickert <jonathan.dickert@protonmail.com>"]
edition = "2021"
default-run = "duck"

[workspace]
members = [".", "macros"]

[[bin]]
name = "duck"
path = "src/main.rs"

[lib]
name = "ducktype"

[workspace.dependencies]
uuid = { version = "1.4", features = ["v4", "macro-diagnostics"] }

[dependencies]
ahash = "0.8"
anyhow = "1.0"
bimap = "0.6"
clap = { version = "4.4", features = ["derive"] }
dlopen2 = "0.6"
enum-map = "2.7"
horrorshow = "0.8"
itertools = "0.11"
lazy-regex = "3.0"
once_cell = "1.18"
rand = "0.8"
regex = "1.10"
rustyline = "12.0"
shellwords = "1.1"
static_assertions = "1.1"
strum = "0.25"
strum_macros = "0.25"
sysinfo = "0.29"
thiserror = "1.0"
uuid = { workspace = true }

pprof = { version = "0.13", features = ["flamegraph"] }
tokio = { version = "1.33", features = ["full"] }
interpolator = "0.5"

ptr = { path = "lib/ptr" }
tfix = { path = "lib/tfix" }
macros = { path = "macros" }

[dev-dependencies]
pretty_assertions = "1.4"
evalexpr = "11.1"

[profile.release]
strip = true
lto = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.48", features = [
  "Win32_Storage_FileSystem",
  "Win32_Foundation",
  "Win32_Security",
] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27", features = ["fs"] }

[features]
visit-ast = []
disassemble = []
runtime-disassembly = []
print-precedence = []
quit-after-disassemble = []

[target.'cfg(unix)'.features]
profile = []
