[package]
name = "simple_script"
version = "0.27.0"
authors = ["Jonathan Dickert <jon.p.dickert@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlopen2 = "*"
enum-iterator = "*"
horrorshow = "*"
inter-struct = "*"
itertools = "*"
memoffset = "*"
rustyline = "12.0.0"
static_assertions = "*"
sysinfo = "*"
thiserror = "*"

ptr = { path = "lib/ptr" }
tfix = { path = "lib/tfix" }
macros = { path = "macros" }

[dev-dependencies]
pretty_assertions = "*"
evalexpr = "11.1.0"

[features]
visit-ast = []
disassemble = []
runtime-disassembly = []
print-precedence = []
quit-after-disassemble = []
