[package]
name = "simple_script"
version = "0.38.0"
authors = ["Jonathan Dickert <jonathan.dickert@protonmail.com>"]
edition = "2021"
default-run = "ss"

[workspace]
members = [".", "macros"]

[workspace.dependencies]
uuid = { version = "1.4.1", features = ["v4", "macro-diagnostics"] }

[[bin]]
name = "ss"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.6", features = ["derive"] }
dlopen2 = "0.6.1"
enum-iterator = "1.4.1"
horrorshow = "0.8.4"
inter-struct = "0.2.0"
itertools = "0.11.0"
memoffset = "0.9.0"
rand = "0.8.5"
rustyline = "12.0.0"
shellwords = "1.1.0"
static_assertions = "1.1.0"
sysinfo = "0.29.10"
thiserror = "1.0.49"
uuid = { workspace = true }

ptr = { path = "lib/ptr" }
tfix = { path = "lib/tfix" }
macros = { path = "macros" }

[dev-dependencies]
pretty_assertions = "1.4.0"
evalexpr = "11.1.0"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.48.0", features = [
  "Win32_Storage_FileSystem",
  "Win32_Foundation",
  "Win32_Security",
] }

[target.'cfg(unix)'.dependencies]
nix = { version = "0.27.1", features = ["fs"] }

[features]
visit-ast = []
disassemble = []
runtime-disassembly = []
print-precedence = []
quit-after-disassemble = []
