[package]
name = "simple_script"
version = "0.20.0"
authors = ["Jonathan Dickert <jon.p.dickert@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ptr = { path = "lib/ptr" }
tfix = { path = "lib/tfix" }
enum-iterator = "*"
static_assertions = "*"
sysinfo = "*"
horrorshow = "*"
itertools = "*"
memoffset = "*"
thiserror = "*"
inter-struct = "*"

macros = { path = "macros" }

[dev-dependencies]
pretty_assertions = "*"
evalexpr = "11.1.0"

[features]
visit-ast = []
disassemble = []
runtime-disassembly = []
quit-after-disassemble = []
