[package]
name = "simple_script"
version = "0.31.0"
authors = ["Jonathan Dickert <jon.p.dickert@gmail.com>"]
edition = "2021"

[workspace]
members = [".", "macros"]

[workspace.dependencies]
uuid = { version = "1.4.1", features = ["v4", "macro-diagnostics"] }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
dlopen2 = "0.6.1"
enum-iterator = "1.4.1"
horrorshow = "0.8.4"
inter-struct = "0.2.0"
itertools = "0.11.0"
memoffset = "0.9.0"
rustyline = "12.0.0"
shellwords = "1.1.0"
static_assertions = "1.1.0"
sysinfo = "0.29.10"
thiserror = "1.0.49"
uuid = { workspace = true }

ptr = { path = "lib/ptr" }
tfix = { path = "lib/tfix" }
macros = { path = "macros" }

[dev-dependencies]
pretty_assertions = "1.4.0"
evalexpr = "11.1.0"

[features]
visit-ast = []
disassemble = []
runtime-disassembly = []
print-precedence = []
quit-after-disassemble = []
